export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/index/index',
    'pages/function/index',
    'pages/profile/index',
    'pages/track/index',
    'pages/settings/index',
    'pages/detail/index',
    'pages/geofence/index',
    'pages/alarm/index',
    'pages/report/index',
    'pages/sim-card/index',
    'pages/add-device/index',
    'pages/share/index',
    'pages/change-password/index',
    'pages/recharge/index',
  ],
  tabBar: {
    color: '#999999',
    selectedColor: '#00C853',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '定位',
        iconPath: 'assets/tab-location.svg',
        selectedIconPath: 'assets/tab-location-active.svg',
      },
      {
        pagePath: 'pages/function/index',
        text: '功能',
        iconPath: 'assets/tab-function.svg',
        selectedIconPath: 'assets/tab-function-active.svg',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tab-profile.svg',
        selectedIconPath: 'assets/tab-profile-active.svg',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#00C853',
    navigationBarTitleText: 'GPS定位器',
    navigationBarTextStyle: 'white',
  },
})
